version: '3.9'

services:
  web:
    build: .
    command: python /testcsv-main/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/testcsv-main
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres


